---
title: "Proyecto Liberia"
author: "Wendy Fonseca"
date: "18/6/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Pasos previos

Primero se agregan los datos con lo que se trabajaran 

```{r message=FALSE, warning=FALSE}
library(ggplot2)
library(dplyr)
library(tidyr)
library(hrbrthemes)
library(gridExtra)

Clima_liberia <- read.csv("liberia_datos_climaticos.csv",sep = ",",na.strings = ""
                          ,dec = ",")

Clima_liberia <- na.omit(Clima_liberia)

Clima_liberia <- Clima_liberia %>%
  rename(Humedad = "HumedadRelativa....",
         Viento = "VelocidadViento..m.s.",
         Lluvia = "Lluvia..mm.",
         Irradiacion = "Irradiacion..W.m2.",
         Evapo = "EvapoTranspiracion..mm.",
         Temperatura = "Temperatura..Celsius.",
         Fecha = "Date"
  )

Clima_liberia <- Clima_liberia %>%
  mutate(Fecha = as.Date(Fecha, format = "%d/%m/%Y"))

```

## Graficos del clima de liberia

Se generan los diferentes graficos de histogramas



```{r fig.height=15, fig.width=10, message=FALSE, warning=FALSE}
lluvia <- ggplot(Clima_liberia,aes(x= Lluvia,group = 1))+geom_histogram(
  color = "blue",
  fill = "blue",
) + 
  ggtitle("mm de lluvia")+
  ylab("")+
  xlab("Lluvia mm")+
  theme_ipsum()
humedad <- ggplot(Clima_liberia,aes(x= Humedad,group = 1))+geom_histogram(
  color = "blue",
  fill = "blue",
) + 
  ggtitle("Porcentaje de humedad")+
  ylab("")+
  xlab("Humedad %")+
  theme_ipsum()
temperatura <- ggplot(Clima_liberia,aes(x= Temperatura,group = 1))+geom_histogram(
  color = "yellow",
  fill = "yellow",
) + 
  ggtitle("Temperatura")+
  ylab("")+
  xlab("Temperatura C°")+
  theme_ipsum()
viento <- ggplot(Clima_liberia,aes(x= Viento,group = 1))+geom_histogram(
  color = "black",
  fill = "grey"
) + 
  ggtitle("Velocidad del viento")+
  ylab("")+
  xlab("Viento (m/s)")+
  theme_ipsum()
irradiacion <- ggplot(Clima_liberia,aes(x= Irradiacion,group = 1))+geom_histogram(
  color = "red",
  fill = "red",
) + 
  ggtitle("Irradiacion")+
  ylab("")+
  xlab("Irradiacion W/m2")+
  theme_ipsum()
evapo <- ggplot(Clima_liberia,aes(x= Evapo,group = 1))+geom_histogram(
  color = "black",
  fill = "grey",
) + 
  ggtitle("Mililitros de evaporacion")+
  ylab("")+
  xlab("Evaporacion ml")+
  theme_ipsum()

grid.arrange(temperatura,humedad,viento,lluvia,irradiacion,evapo,
             nrow = 3, ncol = 2)
```

## Se generan los graficos de lineas


```{r fig.height=15, fig.width=10, message=FALSE, warning=FALSE}
Resumen <-
  Clima_liberia %>%
  select(Fecha, Temperatura,Humedad,Viento, Lluvia, Irradiacion,
         Evapo
         )%>%
  group_by (Fecha = format(Fecha,"%m"))%>%
  summarise(Temperatura = mean(Temperatura),
            Humedad = mean(Humedad),
            Viento = mean(Viento),               
            Lluvia = sum(Lluvia),
            Evapo = sum(Evapo),
            Irradiacion = mean(Irradiacion)
  )

lluviaxmes <- ggplot(Resumen,aes(y= Lluvia,x= Fecha,group = 1))+geom_line(
  color = "blue"
  ) + 
  ggtitle("mm de lluvia")+
  ylab("Lluvia")+
  xlab("Fecha")+
  geom_point()+
  theme_ipsum()

temperaturaxmes <- ggplot(Resumen,aes(y= Temperatura,x= Fecha,group = 1))+geom_line(
  color = "yellow",
) + 
  ggtitle("Temperatura")+
  ylab("Temperatura C°")+
  xlab("Fecha")+
  geom_point()+
  theme_ipsum()


humedadxmes <- ggplot(Resumen,aes(y= Humedad,x= Fecha,group = 1))+geom_line(
  color = "blue"
) + 
  ggtitle("% de Humedad")+
  ylab("Humedad")+
  xlab("Fecha")+
  geom_point()+
  theme_ipsum()


vientoxmes <- ggplot(Resumen,aes(y= Viento,x= Fecha,group = 1))+geom_line(
  color = "blue"
) + 
  ggtitle("Velocidad del viento")+
  ylab("Viento m/s")+
  xlab("Fecha")+
  geom_point()+
  theme_ipsum()

evapoxmes <- ggplot(Resumen,aes(y= Viento,x= Fecha,group = 1))+geom_line(
  color = "blue"
) + 
  ggtitle("Evporacion")+
  ylab("Evaporacion ml")+
  xlab("Fecha")+
  geom_point()+
  theme_ipsum()

irradiacionxmes <- ggplot(Resumen,aes(y= Irradiacion,x= Fecha,group = 1))+geom_line(
  color = "red"
) + 
  ggtitle("Irradiacion")+
  ylab("Irradiacion W/m2")+
  xlab("Fecha")+
  geom_point()+
  theme_ipsum()

grid.arrange(temperaturaxmes,humedadxmes,vientoxmes,
             lluviaxmes,irradiacionxmes,evapoxmes,
             nrow = 3, ncol = 2)

```

## Se generan los graficos de puntos

```{r fig.height=15, fig.width=10, message=FALSE, warning=FALSE}
irradiacionp <- ggplot(Clima_liberia,aes(y= Irradiacion,x= Fecha))+
  geom_point(
    col="red",
    fill= "red"
  ) + 
  ggtitle("Irradiacion")+
  ylab("Irradiacion W/m2")+
  xlab("Fecha")+
  theme_ipsum()

temperaturap <- ggplot(Clima_liberia,aes(y= Temperatura,x= Fecha))+
  geom_point(
    col="yellow",
    fill= "yellow"
  ) + 
  ggtitle("Temperatura")+
  ylab("Temperatura C°")+
  xlab("Fecha")+
  theme_ipsum()

humedadp <- ggplot(Clima_liberia,aes(y= Humedad,x= Fecha))+
  geom_point(
    col="blue",
    fill= "blue"
  ) + 
  ggtitle("% de humedad")+
  ylab("Humedad")+
  xlab("Fecha")+
  theme_ipsum()

vientop <- ggplot(Clima_liberia,aes(y= Viento,x= Fecha))+
  geom_point(
    col="blue",
    fill= "blue"
  ) + 
  ggtitle("Velocidad del viento")+
  ylab("Viento m/s")+
  xlab("Fecha")+
  theme_ipsum()

lluviap <- ggplot(Clima_liberia,aes(y= Lluvia,x= Fecha))+
  geom_point(
    col="black",
    fill= "black"
  ) + 
  ggtitle("Lluvia")+
  ylab("Lluvia mm")+
  xlab("Fecha")+
  theme_ipsum()

evapop <- ggplot(Clima_liberia,aes(y= Evapo,x= Fecha))+
  geom_point(
    col="pink",
    fill= "pink"
  ) + 
  ggtitle("Evaporacion")+
  ylab("Evaporacion ml")+
  xlab("Fecha")+
  theme_ipsum()

grid.arrange(temperaturap,humedadp,vientop,lluviap,
             irradiacionp,evapop,
             nrow = 3, ncol = 2)
```






